# Generated by Django 5.2.8 on 2025-11-25 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='posts_post_search__e0bb56_gin',
        ),
        migrations.RemoveField(
            model_name='post',
            name='search_vector',
        ),
    ]
