# Generated by Django 5.2.8 on 2025-11-26 13:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'follows',
                'indexes': [models.Index(fields=['follower'], name='follows_followe_ca9b09_idx'), models.Index(fields=['followed'], name='follows_followe_a0ecff_idx')],
                'constraints': [models.UniqueConstraint(fields=('follower', 'followed'), name='unique_follow'), models.CheckConstraint(condition=models.Q(('follower', models.F('followed')), _negated=True), name='prevent_self_follow')],
            },
        ),
    ]
