# Generated by Django 5.2.8 on 2025-11-28 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
